ДЗ 1
reatlaz/2022-2-VK-EDU-FS-Frontend-R-AFIATULLOV pull request #1
Opened 2022-10-05 22:23 UTC by reatlaz

Домашнее задание № 1

Прошу @martinkomitsky или @haseprogram проверить его.

Что было сделано:
* Добавлена реализация требуемых функций
* Написаны тесты для `convertBytesToHuman.js`
* Добавлен `.gitignore`

2022-10-10 19:57 UTC, martinkomitsky requested changes
Не добавлен файл package.json

2022-10-10 20:36 UTC, reatlaz commented
> Не добавлен файл package.json
Не совсем понимаю. Вот же он. Просто нету в PR, так как сделали еще на занятии.
![Снимок экрана 2022-10-10 в 23 35 39](https://user-images.githubusercontent.com/68824306/194948504-5ea0738e-0b57-40da-b529-259697756a19.png)

2022-10-10 20:39 UTC, martinkomitsky requested changes
Замечательно, но в ДЗ проверяется в рамках PR. На этот раз ок, но в следующий раз все, что касается ДЗ, надо отправлять на проверку именно в PR.

Увидел, что у тебя закоммичена папка node_modules, что плохо. Ее не нужно хранить в репозитории => удалить, добавить в .gitignore

2022-10-10 20:53 UTC, reatlaz commented
Понял. Немного не разобрался, и все беды пошли от первого коммита до выполнения дз.
В ветке master удалил `node_modules`, в `.gitignore` она уже была.

2022-10-11 06:38 UTC, martinkomitsky approved these changes
ок, 12.
С мастер веткой напрямую не работаем, только через PR

2022-10-11 06:38 UTC, merged