Hw7
reatlaz/2022-2-VK-EDU-FS-Frontend-R-AFIATULLOV pull request #7
Opened 2022-12-12 03:09 UTC by reatlaz

Домашнее задание №7

Прошу @martinkomitsky или @haseprogram проверить его.

Что было сделано:
* Реализовано отправление запросов (post и Polling) на общий бэкэнд.
* Реализовано отправление запросов (post, Polling, getChatInfo) на задеплоенный бэкэнд.
* `localstorage` используется там, где он использовался раньше. Результат запроса информации о чате (для верхнего навбара на странице чата) в `localstorage` не записывается.
* Любой, кто зайдет в задеплоенное приложение на github pages, будет считаться пользователем `guest` и сможет отправлять/просматривать сообщения в обоих бэкэндах.

2022-12-12 12:39 UTC, martinkomitsky requested changes
Сообщения в общем чате идут в обратном порядке, а новые сообщение улетают куда-то выше. Нужно исправить

2022-12-14 10:52 UTC, martinkomitsky requested changes
Сообщения пропадают, а потом появляются, такого быть не должно.
Имени отправителя не видно

2022-12-14 13:16 UTC, reatlaz commented
> Имени отправителя не видно

Разве должно быть видно имя отправителя от лица самого отправителя?
Сообщение же справа. Я специально имя убрал.

2022-12-14 23:07 UTC, martinkomitsky approved these changes
10

2022-12-14 23:07 UTC, merged