Exam
reatlaz/2022-2-VK-EDU-FS-Frontend-R-AFIATULLOV pull request #9
Opened 2022-12-29 17:54 UTC by reatlaz

Экзамен

2022-12-29 17:54 UTC, HaseProgram commented
- [ ] В корневой папке репозитория создать базовое приложение `exam` с помощью [CRA](https://github.com/facebook/create-react-app#quick-overview) по инструкции выше
- [ ] Сверстать 2 страницы и необходимые компоненты. Использовать стили
- [ ] Реализовать перевод с одного языка на другой (хорошо, если можно будет выбрать язык из выпадающего списка)
- [ ] Реализовать перевод с неизвестного языка (автоопределитель из `API`)
- [ ] Сохранять историю переводов в `localStorage`
- [ ] Использовать `Redux`
- [ ] Использовать `React-router` для перехода между страницами
- [ ] Задеплоить решение, используя `GitHub Actions`.
- [ ] Теория: Объяснить, почему были использованы те или иные инструменты, участки кода и механизмы при решении задачи. Ответить на теоретические вопросы (пункт выполняется лично с преподавателем)
- [ ] Ревью: получить правки по коду и исправить их (получаются лично у преподавателя и выполняются самостоятельно)

2022-12-29 18:00 UTC, HaseProgram commented on exam/src/components/Button/Button.jsx
> +        {props.value}
prop.children

2022-12-29 18:14 UTC, HaseProgram requested changes
Доделать оставшееся и тэгнуть на финальную проверку

2022-12-30 15:23 UTC, reatlaz commented
@HaseProgram 
Всё доделал

2022-12-31 13:14 UTC, reatlaz commented
Добавил @martinkomitsky в Reviewers

2022-12-31 14:02 UTC, HaseProgram approved these changes
Привет, супер, 40!

2022-12-31 14:02 UTC, merged